/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#154539",
        "primary-container": "#2f5d50",
        "primary-fixed": "#bceddc",
        "primary-fixed-dim": "#a0d1c0",
        "on-primary": "#ffffff",
        "on-primary-container": "#a3d4c3",
        "on-primary-fixed": "#002019",
        "on-primary-fixed-variant": "#204f42",
        secondary: "#4a6361",
        "secondary-container": "#cae5e2",
        "secondary-fixed": "#cde8e5",
        "secondary-fixed-dim": "#b1ccc9",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#4f6765",
        "on-secondary-fixed": "#061f1e",
        "on-secondary-fixed-variant": "#334b49",
        tertiary: "#5d322a",
        "tertiary-container": "#784840",
        "tertiary-fixed": "#ffdad4",
        "tertiary-fixed-dim": "#f7b7ac",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fbbaaf",
        "on-tertiary-fixed": "#33110b",
        "on-tertiary-fixed-variant": "#683a33",
        surface: "#f9faf7",
        "surface-bright": "#f9faf7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f1",
        "surface-container": "#edeeec",
        "surface-container-high": "#e7e8e6",
        "surface-container-highest": "#e2e3e0",
        "surface-variant": "#e2e3e0",
        "surface-tint": "#396759",
        "surface-dim": "#d9dad8",
        background: "#f9faf7",
        "on-background": "#1a1c1b",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#404945",
        "inverse-surface": "#2e3130",
        "inverse-on-surface": "#f0f1ee",
        "inverse-primary": "#a0d1c0",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#717975",
        "outline-variant": "#c0c8c4",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "container-max": "1280px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        caption: ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      keyframes: {
        scan: {
          "0%": { top: "0%", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { top: "100%", opacity: "0" },
        },
        ping: {
          "75%, 100%": { transform: "scale(2)", opacity: "0" },
        },
      },
      animation: {
        scan: "scan 3s ease-in-out infinite",
        ping: "ping 1.5s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
    },
  },
  plugins: [],
};
